### ISSUE TITLE
MFR api issues

### ISSUE THREAD

**Issue by Leganie** [CoFH/ThermalExpansion-Localization#8]
http://pastebin.com/5feSHYbu

I posted this on ender io git and they closed it claiming it is a broken api from the CoFH team. I updated everything I use from CoFH to the latest as well as ender IO and made sure forge was latest by hand just to check. Wont load period.

https://github.com/CrazyPants/EnderIO/issues/1981

That is their issue track on it and where they claim it is you guys. Honestly I find that hard to believe considering Newest updates are  1-3 days old while ender IO is from the 13th of Feb.

**Comment by Leganie** [comment]
Seems FTB was not updating my packs forge properly sorry.

**Comment by HenryLoenwind** [comment]
@Leganie If you look at your log, you'll see a line:

    EnderIO{1.7.10-2.2.8.349} [Ender IO] (EnderIO-1.7.10-2.2.8.349.jar) Unloaded

That means that Ender IO has not even been loaded when the crash occurs.
